### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by GuangchuangYu** [richfitz/remoji#5]
OS X support emoji, and `remoji` works fine in R console.
![emoji](https://cloud.githubusercontent.com/assets/626539/10960947/43712628-83c4-11e5-9cb7-390c7751c08d.jpg)

But if I try to plot them by base plot or ggplot, it fails.

In linux, after I installed `ttf-ancient-fonts`, `emoji` works fine in both console and plot.

I want to produce `phylomoji` with `ggtree`:
![](https://pbs.twimg.com/media/CTA78bwUEAAUCB2.png:large)

It seems that in OS X, the plotting system, base or grid, can't recognize AppleEmoji font.

Any idea?

**Comment by richfitz** [comment]
It's possible something in the approach here could work: http://blog.revolutionanalytics.com/2012/09/how-to-use-your-favorite-fonts-in-r-charts.html

**Comment by GuangchuangYu** [comment]
I did try, but it seems that both `showtext` and `extrafont` can't import `/System/Library/Fonts/Apple Color Emoji.ttf`.

**Comment by richfitz** [comment]
hmm, it might be a limitation of the quartz device as this works on OSX (quartz) and Linux (X11)

``` r
> plot(1:10, pch=-0x2642L)
```

while this only works on Linux

```
> plot(1:10, pch=-0x1f321L)
```

On OSX neither work to PDF (via `pdf` and `cairo_pdf`).

**Comment by GuangchuangYu** [comment]
FYI, the above figure produce in OSX using [OpenSansEmoji](https://github.com/MorbZ/OpenSansEmoji), which can be imported by `showtext` but fail with `extrafont`.

**Comment by GuangchuangYu** [comment]
Hi @richfitz , I created the [emojifont](https://github.com/GuangchuangYu/emojifont) package to support using emoji font.
